version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      python-deps:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /cdk
    schedule:
      interval: monthly
    versioning-strategy: lockfile-only
    groups:
      node-deps:
        patterns:
          - "*"
