repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args:
          - --branch
          - main
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.48.0
    hooks:
      - id: eslint
        files: cdk/(bin|lib)/.+\.ts$
        types:
          - file
        args:
          - -c
          - ./cdk/.eslintrc.js
          - --fix
