site_name: Nintendo 64 End Labels
site_url: https://n64.hackerman.ca/
repo_url: https://github.com/daxAKAhackerman/n64-label-templates
repo_name: daxAKAhackerman/n64-label-templates
site_description: Nintendo 64 end labels for all games that you can download, edit and print yourself
site_author: Samuel De Grace
nav:
  - Home: index.md
  - Templates:
    - ntsc-u.md
    - ntsc-u-exclusives.md
    - ntsc-u-variants.md
    - ntsc-j.md
    - ntsc-j-exclusives.md
    - ntsc-j-variants.md
    - pal.md
    - pal-exclusives.md
    - pal-variants.md
    - third-party.md
theme:
  name: simple-blog
  favicon: img/favicon.ico
  logo: img/logo.png
  components:
    title: false
    preview: false
    footer: false
